tools/power turbostat: Fix build with musl
mainline inclusion
from mainline-v6.17-rc1
commit 6ea0ec1b958a84aff9f03fb0ae4613a4d5bed3ea
category: feature
bugzilla: https://atomgit.com/openeuler/intel-kernel/issues/201
CVE: NA
Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6ea0ec1b958a84aff9f03fb0ae4613a4d5bed3ea

-------------------------------------------------

Intel-SIG: commit 6ea0ec1b958a tools/power turbostat: Fix build with musl
Sync turbostat to version 2025.12.02

turbostat.c: In function 'parse_int_file':
    turbostat.c:5567:19: error: 'PATH_MAX' undeclared (first use in this function)
     5567 |         char path[PATH_MAX];
          |                   ^~~~~~~~

    turbostat.c: In function 'probe_graphics':
    turbostat.c:6787:19: error: 'PATH_MAX' undeclared (first use in this function)
     6787 |         char path[PATH_MAX];
          |                   ^~~~~~~~

Signed-off-by: Calvin Owens <calvin@wbinvd.org>
Reviewed-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>
Signed-off-by: Len Brown <len.brown@intel.com>
[ Zhang Rui: amend commit log ]
Signed-off-by: Zhang Rui <rui.zhang@intel.com>