ACPI: APEI: EINJ: mark remove callback as non-__exit
mainline inclusion
from mainline-v6.9-rc2
commit a24118a8a6870fe06dbbd59f915b9ca3662b2ddb
category: feature
bugzilla: https://atomgit.com/openeuler/intel-kernel/issues/188
CVE: NA
Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a24118a8a6870fe06dbbd59f915b9ca3662b2ddb

-------------------------------------------------

Intel-SIG: commit a24118a8a687 ACPI: APEI: EINJ: mark remove callback as non-__exit
Backport APEI EINJ V2 support

The remove callback of a device is called whenever it is unbound,
which may happen during runtime e.g. through sysfs, so this is not
allowed to be dropped from the binary:

WARNING: modpost: vmlinux: section mismatch in reference: einj_driver+0x8 (section: .data) -> einj_remove (section: .exit.text)
ERROR: modpost: Section mismatches detected.

Remove that annotation.

Fixes: 12fb28ea6b1c ("EINJ: Add CXL error type support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Dan Williams <dan.j.williams@intel.com>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
[ Zhang Rui: amend commit log ]
Signed-off-by: Zhang Rui <rui.zhang@intel.com>