Revert "resctrl: fix undefined reference to lockdep_is_cpus_held()"
Intel inclusion
category: feature
bugzilla: https://gitee.com/openeuler/kernel/issues/8967

---------------------------

This reverts commit bd3178be4de25d611941a2c021d7e0155a95c805.

Signed-off-by: Jason Zeng <jason.zeng@intel.com>